### ISSUE TITLE
I can't get mytv/gotv video path as before

### ISSUE THREAD

**Issue by rainy3519446** [hklcf/myTV-api#3]
之前可以从http://api.mytv.tvb.com/rest_search_api/data_video/format/json/id/{video_id}
中提取组合到视频hls的下载地址，但是5月20日之后tvb似乎封了这个接口，该接口不再返回hls直播的地址，请问还有其他地址吗？谢谢

**Comment by adamcheng1947** [comment]
@rainy3519446 我都是一样，不过现在如果楼主发出新的方法一定TVB会再做保密了，我以为楼主已经被TVB的人跟踪调查

**Comment by rainy3519446** [comment]
@adamcheng1947 你有新方法吗？

**Comment by hklcf** [comment]
tvb封了

**Comment by adamcheng1947** [comment]
@rainy3519446 ：当然没有啦，我们现在只有等，过几个星期后再算

**Comment by hk520** [comment]
mytvsuper上的点播视频怎么下载，找到了后半段的smil地址，接下来的不知道怎么构造视频地址了。。

**Comment by renwokuang** [comment]
mytvsuper上的点播视频怎么下载，找到了后半段的smil地址，接下来的不知道怎么构造视频地址了。。
