### ISSUE TITLE
Get link GOTV

### ISSUE THREAD

**Issue by schtroumpfs** [hklcf/myTV-api#8]
could you please show me how to get this series?
Thank you so much

http://gotv.tvb.com/programme/102391

**Comment by hklcf** [comment]
ep43 video_id=155571

http://orbit8-1.hk4.tvb.com/session/55251ee2-5bb4-11e6-937f-005056902609/5waie8/vipo_audioindex0/_definst_/vipo/he2/1207/120657/000000270879.smil/playlist.m3u8?audioindex=0

session will expire soon

sorry, i can't tell you anything in this moment.

**Comment by schtroumpfs** [comment]
could you please tell me how to get video? my email: bvlt2003@yahoo.com
